export interface Currency {
  code: string;
  symbol: string;
  name: string;
}

/** Shown as quick-pick chips before the "More" list. */
export const SUGGESTED_CURRENCIES: Currency[] = [
  { code: "USD", symbol: "$", name: "US Dollar" },
  { code: "EUR", symbol: "€", name: "Euro" },
  { code: "GBP", symbol: "£", name: "British Pound" },
];

export const ALL_CURRENCIES: Currency[] = [
  ...SUGGESTED_CURRENCIES,
  { code: "JPY", symbol: "¥", name: "Japanese Yen" },
  { code: "AUD", symbol: "A$", name: "Australian Dollar" },
  { code: "CAD", symbol: "C$", name: "Canadian Dollar" },
  { code: "CHF", symbol: "Fr", name: "Swiss Franc" },
  { code: "CNY", symbol: "¥", name: "Chinese Yuan" },
  { code: "SGD", symbol: "S$", name: "Singapore Dollar" },
  { code: "HKD", symbol: "HK$", name: "Hong Kong Dollar" },
  { code: "NZD", symbol: "NZ$", name: "New Zealand Dollar" },
  { code: "INR", symbol: "₹", name: "Indian Rupee" },
  { code: "MXN", symbol: "MX$", name: "Mexican Peso" },
  { code: "PHP", symbol: "₱", name: "Philippine Peso" },
  { code: "THB", symbol: "฿", name: "Thai Baht" },
  { code: "IDR", symbol: "Rp", name: "Indonesian Rupiah" },
  { code: "KRW", symbol: "₩", name: "South Korean Won" },
  { code: "ZAR", symbol: "R", name: "South African Rand" },
  { code: "BRL", symbol: "R$", name: "Brazilian Real" },
  { code: "AED", symbol: "AED", name: "UAE Dirham" },
  { code: "AFN", symbol: "AFN", name: "Afghan Afghani" },
  { code: "ALL", symbol: "ALL", name: "Albanian Lek" },
  { code: "AMD", symbol: "AMD", name: "Armenian Dram" },
  { code: "AOA", symbol: "AOA", name: "Angolan Kwanza" },
  { code: "ARS", symbol: "AR$", name: "Argentine Peso" },
  { code: "AWG", symbol: "AWG", name: "Aruban Florin" },
  { code: "AZN", symbol: "AZN", name: "Azerbaijani Manat" },
  { code: "BAM", symbol: "BAM", name: "Bosnia-Herzegovina Mark" },
  { code: "BBD", symbol: "BBD", name: "Barbadian Dollar" },
  { code: "BDT", symbol: "৳", name: "Bangladeshi Taka" },
  { code: "BGN", symbol: "BGN", name: "Bulgarian Lev" },
  { code: "BHD", symbol: "BHD", name: "Bahraini Dinar" },
  { code: "BIF", symbol: "BIF", name: "Burundian Franc" },
  { code: "BMD", symbol: "BMD", name: "Bermudan Dollar" },
  { code: "BND", symbol: "BND", name: "Brunei Dollar" },
  { code: "BOB", symbol: "BOB", name: "Bolivian Boliviano" },
  { code: "BSD", symbol: "BSD", name: "Bahamian Dollar" },
  { code: "BTN", symbol: "BTN", name: "Bhutanese Ngultrum" },
  { code: "BWP", symbol: "BWP", name: "Botswanan Pula" },
  { code: "BYN", symbol: "BYN", name: "Belarusian Ruble" },
  { code: "BZD", symbol: "BZD", name: "Belize Dollar" },
  { code: "CDF", symbol: "CDF", name: "Congolese Franc" },
  { code: "CLP", symbol: "CLP", name: "Chilean Peso" },
  { code: "COP", symbol: "COP", name: "Colombian Peso" },
  { code: "CRC", symbol: "₡", name: "Costa Rican Colón" },
  { code: "CUP", symbol: "CUP", name: "Cuban Peso" },
  { code: "CVE", symbol: "CVE", name: "Cape Verdean Escudo" },
  { code: "CZK", symbol: "Kč", name: "Czech Koruna" },
  { code: "DJF", symbol: "DJF", name: "Djiboutian Franc" },
  { code: "DKK", symbol: "kr", name: "Danish Krone" },
  { code: "DOP", symbol: "DOP", name: "Dominican Peso" },
  { code: "DZD", symbol: "DZD", name: "Algerian Dinar" },
  { code: "EGP", symbol: "EGP", name: "Egyptian Pound" },
  { code: "ERN", symbol: "ERN", name: "Eritrean Nakfa" },
  { code: "ETB", symbol: "ETB", name: "Ethiopian Birr" },
  { code: "FJD", symbol: "FJD", name: "Fijian Dollar" },
  { code: "FKP", symbol: "FKP", name: "Falkland Islands Pound" },
  { code: "GEL", symbol: "GEL", name: "Georgian Lari" },
  { code: "GHS", symbol: "GHS", name: "Ghanaian Cedi" },
  { code: "GIP", symbol: "GIP", name: "Gibraltar Pound" },
  { code: "GMD", symbol: "GMD", name: "Gambian Dalasi" },
  { code: "GNF", symbol: "GNF", name: "Guinean Franc" },
  { code: "GTQ", symbol: "GTQ", name: "Guatemalan Quetzal" },
  { code: "GYD", symbol: "GYD", name: "Guyanaese Dollar" },
  { code: "HNL", symbol: "HNL", name: "Honduran Lempira" },
  { code: "HTG", symbol: "HTG", name: "Haitian Gourde" },
  { code: "HUF", symbol: "Ft", name: "Hungarian Forint" },
  { code: "ILS", symbol: "₪", name: "Israeli New Shekel" },
  { code: "IQD", symbol: "IQD", name: "Iraqi Dinar" },
  { code: "IRR", symbol: "IRR", name: "Iranian Rial" },
  { code: "ISK", symbol: "ISK", name: "Icelandic Króna" },
  { code: "JMD", symbol: "JMD", name: "Jamaican Dollar" },
  { code: "JOD", symbol: "JOD", name: "Jordanian Dinar" },
  { code: "KES", symbol: "KES", name: "Kenyan Shilling" },
  { code: "KGS", symbol: "KGS", name: "Kyrgystani Som" },
  { code: "KHR", symbol: "KHR", name: "Cambodian Riel" },
  { code: "KMF", symbol: "KMF", name: "Comorian Franc" },
  { code: "KPW", symbol: "KPW", name: "North Korean Won" },
  { code: "KWD", symbol: "KWD", name: "Kuwaiti Dinar" },
  { code: "KYD", symbol: "KYD", name: "Cayman Islands Dollar" },
  { code: "KZT", symbol: "KZT", name: "Kazakhstani Tenge" },
  { code: "LAK", symbol: "LAK", name: "Laotian Kip" },
  { code: "LBP", symbol: "LBP", name: "Lebanese Pound" },
  { code: "LKR", symbol: "LKR", name: "Sri Lankan Rupee" },
  { code: "LRD", symbol: "LRD", name: "Liberian Dollar" },
  { code: "LSL", symbol: "LSL", name: "Lesotho Loti" },
  { code: "LYD", symbol: "LYD", name: "Libyan Dinar" },
  { code: "MAD", symbol: "MAD", name: "Moroccan Dirham" },
  { code: "MDL", symbol: "MDL", name: "Moldovan Leu" },
  { code: "MGA", symbol: "MGA", name: "Malagasy Ariary" },
  { code: "MKD", symbol: "MKD", name: "Macedonian Denar" },
  { code: "MMK", symbol: "MMK", name: "Myanma Kyat" },
  { code: "MNT", symbol: "MNT", name: "Mongolian Tugrik" },
  { code: "MOP", symbol: "MOP", name: "Macanese Pataca" },
  { code: "MRU", symbol: "MRU", name: "Mauritanian Ouguiya" },
  { code: "MUR", symbol: "MUR", name: "Mauritian Rupee" },
  { code: "MVR", symbol: "MVR", name: "Maldivian Rufiyaa" },
  { code: "MWK", symbol: "MWK", name: "Malawian Kwacha" },
  { code: "MYR", symbol: "RM", name: "Malaysian Ringgit" },
  { code: "MZN", symbol: "MZN", name: "Mozambican Metical" },
  { code: "NAD", symbol: "NAD", name: "Namibian Dollar" },
  { code: "NGN", symbol: "₦", name: "Nigerian Naira" },
  { code: "NIO", symbol: "NIO", name: "Nicaraguan Córdoba" },
  { code: "NOK", symbol: "kr", name: "Norwegian Krone" },
  { code: "NPR", symbol: "NPR", name: "Nepalese Rupee" },
  { code: "OMR", symbol: "OMR", name: "Omani Rial" },
  { code: "PAB", symbol: "PAB", name: "Panamanian Balboa" },
  { code: "PEN", symbol: "PEN", name: "Peruvian Sol" },
  { code: "PGK", symbol: "PGK", name: "Papua New Guinean Kina" },
  { code: "PKR", symbol: "PKR", name: "Pakistani Rupee" },
  { code: "PLN", symbol: "zł", name: "Polish Złoty" },
  { code: "PYG", symbol: "PYG", name: "Paraguayan Guarani" },
  { code: "QAR", symbol: "QAR", name: "Qatari Rial" },
  { code: "RON", symbol: "RON", name: "Romanian Leu" },
  { code: "RSD", symbol: "RSD", name: "Serbian Dinar" },
  { code: "RUB", symbol: "₽", name: "Russian Ruble" },
  { code: "RWF", symbol: "RWF", name: "Rwandan Franc" },
  { code: "SAR", symbol: "SAR", name: "Saudi Riyal" },
  { code: "SBD", symbol: "SBD", name: "Solomon Islands Dollar" },
  { code: "SCR", symbol: "SCR", name: "Seychellois Rupee" },
  { code: "SDG", symbol: "SDG", name: "Sudanese Pound" },
  { code: "SEK", symbol: "kr", name: "Swedish Krona" },
  { code: "SHP", symbol: "SHP", name: "Saint Helena Pound" },
  { code: "SLE", symbol: "SLE", name: "Sierra Leonean Leone" },
  { code: "SOS", symbol: "SOS", name: "Somali Shilling" },
  { code: "SRD", symbol: "SRD", name: "Surinamese Dollar" },
  { code: "SSP", symbol: "SSP", name: "South Sudanese Pound" },
  { code: "STN", symbol: "STN", name: "São Tomé & Príncipe Dobra" },
  { code: "SYP", symbol: "SYP", name: "Syrian Pound" },
  { code: "SZL", symbol: "SZL", name: "Swazi Lilangeni" },
  { code: "TJS", symbol: "TJS", name: "Tajikistani Somoni" },
  { code: "TMT", symbol: "TMT", name: "Turkmenistani Manat" },
  { code: "TND", symbol: "TND", name: "Tunisian Dinar" },
  { code: "TOP", symbol: "TOP", name: "Tongan Paʻanga" },
  { code: "TRY", symbol: "₺", name: "Turkish Lira" },
  { code: "TTD", symbol: "TTD", name: "Trinidad & Tobago Dollar" },
  { code: "TWD", symbol: "NT$", name: "New Taiwan Dollar" },
  { code: "TZS", symbol: "TZS", name: "Tanzanian Shilling" },
  { code: "UAH", symbol: "₴", name: "Ukrainian Hryvnia" },
  { code: "UGX", symbol: "UGX", name: "Ugandan Shilling" },
  { code: "UYU", symbol: "UYU", name: "Uruguayan Peso" },
  { code: "UZS", symbol: "UZS", name: "Uzbekistan Som" },
  { code: "VES", symbol: "VES", name: "Venezuelan Bolívar" },
  { code: "VND", symbol: "₫", name: "Vietnamese Dong" },
  { code: "VUV", symbol: "VUV", name: "Vanuatu Vatu" },
  { code: "WST", symbol: "WST", name: "Samoan Tala" },
  { code: "XAF", symbol: "XAF", name: "Central African CFA Franc" },
  { code: "XCD", symbol: "XCD", name: "East Caribbean Dollar" },
  { code: "XOF", symbol: "XOF", name: "West African CFA Franc" },
  { code: "XPF", symbol: "XPF", name: "CFP Franc" },
  { code: "YER", symbol: "YER", name: "Yemeni Rial" },
  { code: "ZMW", symbol: "ZMW", name: "Zambian Kwacha" },
  { code: "ZWL", symbol: "ZWL", name: "Zimbabwean Dollar" },
];

export function currencySymbol(code: string): string {
  return ALL_CURRENCIES.find((c) => c.code === code)?.symbol ?? code;
}
